apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-iceberg-config
data:
  spark-defaults.conf: |
    spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
    spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog
    spark.sql.catalog.my_catalog.type=jdbc
    spark.sql.catalog.my_catalog.uri=jdbc:postgresql://postgres:5432/product_catalog
    spark.sql.catalog.my_catalog.jdbc.user=boutique
    spark.sql.catalog.my_catalog.jdbc.password=boutique_pass
    spark.sql.catalog.my_catalog.warehouse=s3a://iceberg-warehouse/
    spark.sql.catalog.my_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO
    spark.hadoop.fs.s3a.endpoint=http://minio:9000
    spark.hadoop.fs.s3a.access.key=admin
    spark.hadoop.fs.s3a.secret.key=admin123
    spark.hadoop.fs.s3a.path.style.access=true
